name: blockdevice
version: 0.0.1
main: yolfry\blockdevice\Main
api: 4.6.1
src-namespace-prefix: yolfry\blockdevice

author: Yolfry Bautista
description: Permite blockar dipositivos 
website: https://github.com/pmmp/ExamplePlugin